[files]
extend-exclude = [
  "benchmark/testdata/*",
  "docs/benchmarks/report.md",
  # external code
  "qotp/*",
  # Do not self-check
  "typos.toml",
]

[default.extend-words]
qotp = "qotp"
qh = "qh"
